name: Node CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v**"
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        package-name:
          - "@sofie-prompter-editor/shared-model"
          - "@sofie-prompter-editor/shared-lib"
          - "@sofie-prompter-editor/apps-app"
          - "@sofie-prompter-editor/apps-backend"
          - "@sofie-prompter-editor/apps-client"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: corepack enable
      - name: Prepare Environment
        run: |
          yarn install
          yarn lerna run --scope ${{ matrix.package-name }} --include-dependencies --stream build
        env:
          CI: true
      - name: Run typecheck and linter
        run: |
          yarn lerna run --scope ${{ matrix.package-name }} --stream lint
        env:
          CI: true

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        package-name:
          - "@sofie-prompter-editor/shared-model"
          - "@sofie-prompter-editor/shared-lib"
          - "@sofie-prompter-editor/apps-app"
          - "@sofie-prompter-editor/apps-backend"
          - "@sofie-prompter-editor/apps-client"

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: corepack enable
      - name: Prepare Environment
        run: |
          yarn install
          yarn lerna run --scope ${{ matrix.package-name }} --include-dependencies --stream build
        env:
          CI: true
      - name: Run tests
        run: |
          yarn lerna run --scope ${{ matrix.package-name }} --stream test
        env:
          CI: true
